Stop "Missing initializer in const declaration“ in user test.
Fix to stop
“const db;
      ^^
SyntaxError: Missing initializer in const declaration“